export const SIGNAL_CONFIG = {
  ADP_NOTABLE_MOVE: 5,
  ADP_STRONG_MOVE: 10,
  WAIVER_SURGE_MIN_NET: 5_000,
  WAIVER_ACCELERATION_MULTIPLIER: 2,
  EARLY_ADP_STABILITY: 3,
  EARLY_RECENT_NET: 5_000,
  SCORE_ADP_MAX: 30,
  SCORE_WAIVER_MAX: 30,
  SCORE_ACCELERATION_MAX: 20,
  SCORE_CONFIRMATION_MAX: 20,
  VELOCITY_RECENT_HOURS: 6,
  VELOCITY_BASELINE_HOURS: 24,
  STATS_USAGE_RISE_MIN: 0.15,
  STATS_TREND_MIN_GAMES: 2
} as const;

export type AccelerationLabel = 'ACCELERATING' | 'STEADY' | 'DECELERATING' | 'N/A';
